# Deploy static content from another repository to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout love-app repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/love-app
          ref: main
          path: love-app
          token: ${{ secrets.LOVE_APP_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: love-app

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
